version: '3'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: devsecret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    ports:
      - "54320:5432"
    volumes: 
      - "./.docker/dbdata:/var/lib/postgresql/data"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web

# # docker-compose.yaml
# version: '3'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: app
#     tty: true
#     depends_on:
#       - db
#     environment:
#       - "DB_PORT=5432"
#       - "DB_HOST=db"
#       - "DB_USER=devuser"
#       - "DB_PASS=devsecret"
#       - "DB_DATABASE=devdb"
#     working_dir: /var/www
#     volumes:
#       - ./:/var/www

#   webserver:
#     image: nginx:stable
#     container_name: webserver
#     restart: always
#     ports:
#       - "8080:80"
#     depends_on:
#       - app
#     volumes:
#       - ./:/var/www
#       - ./app.conf:/etc/nginx/conf.d/default.conf
#     links:
#       - app

#   db:
#     image: postgres:12
#     container_name: db
#     restart: always
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: devsecret
#       POSTGRES_USER: devuser
#       POSTGRES_DB: devdb
#     ports:
#       - "54320:5432"

#   dbtest:
#     image: postgres:12
#     container_name: dbtest
#     restart: always
#     volumes:
#       - db_data_test:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: testsecret
#       POSTGRES_USER: testuser
#       POSTGRES_DB: testdb
#     ports:
#       - "54321:5432"

# volumes:
#   db_data:
#   db_data_test: